export const ADD_TO_CART_REQUEST = "ADD_TO_CART_REQUEST";

export const ADD_TO_CART_SUCCESS = "ADD_TO_CART_SUCCESS";

export const ADD_TO_CART_FAILURE = "ADD_TO_CART_FAILURE";

export const REMOVE_CART_ITEM_REQUEST = "REMOVE_CART_ITEM_REQUEST";

export const REMOVE_CART_ITEM_SUCCESS = "REMOVE_CART_ITEM_SUCCESS";

export const REMOVE_CART_ITEM_FAILURE = "REMOVE_CART_ITEM_FAILURE";

export const SAVE_SHIPPING_INFO_REQUEST = "SAVE_SHIPPING_INFO_REQUEST";

export const SAVE_SHIPPING_INFO_SUCCESS = "SAVE_SHIPPING_INFO_SUCCESS";

export const SAVE_SHIPPING_INFO_FAILURE = "SAVE_SHIPPING_INFO_FAILURE";

export const UPDATE_CART_ITEM_OPTIMISTIC = "UPDATE_CART_ITEM_OPTIMISTIC";

export const UPDATE_CART_ITEM_SUCCESS = "UPDATE_CART_ITEM_SUCCESS";

export const UPDATE_CART_ITEM_FAILURE = "UPDATE_CART_ITEM_FAILURE";

export const CLEAR_ERRORS = "CLEAR_ERRORS";

export const SET_INITIAL_PRODUCTS = "SET_INITIAL_PRODUCTS";

export const GET_CART_ITEMS_REQUEST = "GET_CART_ITEMS_REQUEST";

export const GET_CART_ITEMS_SUCCESS = "GET_CART_ITEMS_SUCCESS";

export const GET_CART_ITEMS_FAILURE = "GET_CART_ITEMS_FAILURE";

export const CLEAR_CART_REQUEST = "CLEAR_CART_REQUEST";

export const CLEAR_CART_SUCCESS = "CLEAR_CART_SUCCESS";

export const CLEAR_CART_FAILURE = "CLEAR_CART_FAILURE";

export const SELECT_ALL_CART_ITEMS = "SELECT_ALL_CART_ITEMS";

export const UNSELECT_ALL_CART_ITEMS = "UNSELECT_ALL_CART_ITEMS";
