export const INIT_CHECKOUT_REQUEST = 'INIT_CHECKOUT_REQUEST';
export const INIT_CHECKOUT_SUCCESS = 'INIT_CHECKOUT_SUCCESS';
export const INIT_CHECKOUT_FAILURE = 'INIT_CHECKOUT_FAILURE';

export const SET_SHIPPING_ADDRESS_REQUEST = 'SET_SHIPPING_ADDRESS_REQUEST';
export const SET_SHIPPING_ADDRESS_SUCCESS = 'SET_SHIPPING_ADDRESS_SUCCESS';
export const SET_SHIPPING_ADDRESS_FAILURE = 'SET_SHIPPING_ADDRESS_FAILURE';

export const SET_CHECKOUT_STEP = 'SET_CHECKOUT_STEP';
export const RESET_CHECKOUT = 'RESET_CHECKOUT';