export const KAKAOPAYMENT_READY_REQUEST = "KAKAOPAYMENT_READY_REQUEST";
export const KAKAOPAYMENT_READY_SUCCESS = "KAKAOPAYMENT_READY_SUCCESS";
export const KAKAOPAYMENT_READY_FAILURE = "KAKAOPAYMENT_READY_FAILURE";

export const KAKAOPAYMENT_APPROVE_REQUEST = "KAKAOPAYMENT_APPROVE_REQUEST";
export const KAKAOPAYMENT_APPROVE_SUCCESS = "KAKAOPAYMENT_APPROVE_SUCCESS";
export const KAKAOPAYMENT_APPROVE_FAILURE = "KAKAOPAYMENT_APPROVE_FAILURE";
export const CLEAR_PAYMENT_STATE = "CLEAR_PAYMENT_STATE";
