name: Deploy React App to S3

on:
  push:
    branches:
      - main  # Only trigger on pushes to main branch
  pull_request:
    branches:
      - main  # Only trigger on pull requests to main branch

permissions:
  id-token: write
  contents: read

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18" # or whatever version you're using

      - name: Install dependencies
        run: npm ci

      - name: Create env file
        run: |
          echo "REACT_APP_API_URL=${{ secrets.REACT_APP_API_URL }}" >> .env

      - name: Clear build cache
        run: |
          rm -rf build
          rm -rf node_modules/.cache

      - name: Build React app
        run: CI=false npm run build
        env:
          REACT_APP_API_URL: ${{ secrets.REACT_APP_API_URL }}

      - name: Configure AWS credentials
        if: github.ref == 'refs/heads/main'
        uses: aws-actions/configure-aws-credentials@v3
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Deploy to S3
        if: github.ref == 'refs/heads/main'
        run: aws s3 sync build/ s3://${{ secrets.S3_BUCKET }} --delete

      - name: Invalidate CloudFront cache
        if: github.ref == 'refs/heads/main'
        run: aws cloudfront create-invalidation --distribution-id ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }} --paths "/*"

  create-pr:
    needs: build-and-deploy
    if: github.ref == 'refs/heads/dev'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.REPOSITORY_TOKEN }}
          branch: main
          base: dev
          title: "Merge dev into main"
          body: "Automated PR to merge dev into main"
